Add RenderLive
WeLightProject/Tai-Shang-Soul-Card pull request #39
Opened 2022-06-28 14:31 UTC by kenspirit

2022-06-28 15:14 UTC, zhenfeng-zhu requested changes

2022-06-28 15:14 UTC, zhenfeng-zhu commented on contents/SoulCard - RenderLive.md
> +### LiveView
是不是一级标题就可以呀

2022-06-28 15:14 UTC, zhenfeng-zhu commented on contents/SoulCard - RenderLive.md
> +这里需要指出的是，模板是通过 `Code.eval_quoted/3` 动态执行外部文件的代码来实现的，所以有很大安全风险，必须确保外部文件不包含恶意代码。所以，必须确保外部代码可控，且无法被篡改，比如保存在 IPFS，或 Arweave 区块链上。
这里多了一个逗号

2022-06-28 15:14 UTC, zhenfeng-zhu commented on contents/SoulCard - RenderLive.md
> +`template` 是合法的 Heex 模板或者 HTML 文件就可以了。`SoulCardRenderLive` 是从 `assigns.template_gist_id` 指定的 Gist 读取的。可以参考这个样例：https://gist.github.com/leeduckgo/1a301c084577fde54df73ced3139a3cb
markdown超链接的方式会更好

2022-06-28 15:14 UTC, zhenfeng-zhu commented on contents/SoulCard - RenderLive.md
> +### 详解 CodesOnChain.SoulCardRenderLive
可以在这里补充一个流程图

2022-06-29 05:40 UTC, kenspirit commented on contents/SoulCard - RenderLive.md
> +### 详解 CodesOnChain.SoulCardRenderLive
什么流程图？

2022-07-02 03:07 UTC, kenspirit commented on contents/SoulCard - RenderLive.md
> +### LiveView
因为没有确定每篇文章怎么组合，我只是随便分隔一下，最后会调整的。

2022-07-02 03:17 UTC, zhenfeng-zhu commented on contents/SoulCard - RenderLive.md
> +### 详解 CodesOnChain.SoulCardRenderLive
简单画一个请求流图吧

2022-07-11 12:21 UTC, merged